### ISSUE TITLE
Client credentials flow: auth.authenticate() with no args not working as shown in documentation example

### ISSUE THREAD

**Issue by blaiszik** [Mendeley/mendeley-python-sdk#1]
TypeError: authenticate() takes exactly 2 arguments (1 given)

```
from mendeley import Mendeley

# These values should match the ones supplied when registering your application.
mendeley = Mendeley(client_id, client_secret=client_secret)

auth = mendeley.start_implicit_grant_flow()
session = auth.authenticate()
```

**Comment by dilip89** [comment]
Hi, I am also getting the same error. (Missing token error for auth.authenticate() ). I also changed auth to mendeley.start_client_credentials_flow() but the error still persist. Please advise. 

Also do we need to supply login credentials for any authentication. There is no proper documentation for this method.
