### ISSUE TITLE
General import failure

### ISSUE THREAD

**Issue by mschmidt-umc** [Mendeley/mendeley-python-sdk#14]
I'm working on a django app using the mendeley api. I've done the following:

    $ pip install mendeley

In my code, simplified:

    from mendeley import Mendeley

I get the error, "Cannot import name 'Mendeley'" I have tried this upper-case, lower-case, tried just importing mendeley without the "from" (which works, but I can't figure out how to refer to anything beyond that. I'm happy to help or fix the docs when I figure out what's wrong, but I'm stuck before I've done anything.

**Comment by mfschmidt** [comment]
My problem was that I called my own django app "mendeley" so when I imported mendeley, I got my own app instead of the external one I wanted. To avoid this namespace clash, I renamed my own app and all was fine.

**Comment by Joyce-Stack** [comment]
Thank you for the feedback on this. I will now close this issue.
