### ISSUE TITLE
Searching with "AND", "OR", and "-" through the API

### ISSUE THREAD

**Issue by andredozier** [Mendeley/mendeley-python-sdk#5]
This is a backend issue on Mendeley's servers, I know.... Please let me know if you already have an option for performing "All-And" catalog searches, but as far as I can see when playing with the API is that "Any-Or" is the only one that currently seems to work. Can you implement in the "search/catalog" API an option to search with intersections instead of just unions (within a single query string AND ALSO across catalog document attributes). For example, a search for "particle swarm optimization" searches all documents for "particle", "swarm", or "optimization" instead of all-and. Also, if I want to filter to a specific field or publication by setting the "source" parameter to "water resources planning and management", for example, then currently I get ANY document that contains a match in "source" for "water", "resources", "planning", or "management" instead of actually filtering the results. I would think it would be a trivial task to provide an option for performing "All-And" searches instead of "Any-Or", especially since the main site already performs those types of searches.

**Comment by MendeleyStack** [comment]
Hello, 

Apologies for the extremely long delay. 

Have you seen the Advanced Search Options on our developer portal? -http://dev.mendeley.com/getting_started/common_tasks.html#advanced

**Comment by andredozier** [comment]
Thanks. That would have been nice to know 7-8 months ago, but I ended up 
using the Thomson-Reuters Web of Science database to get what I needed.

Thanks again,

André

**Comment by MendeleyStack** [comment]
Apologies once again.
